import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* Load THREEJS before AMI */}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r81/three.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/ami.js/0.0.12/ami.min.js"></script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
